### ISSUE TITLE
Symfony 3 compatibility

### ISSUE THREAD

**Issue by magnetik** [GlobalTradingTechnologies/reverse-search-acl#1]
Hi,

Is this bundle compatible with symfony 3 ?

Another little question : aren't there any way for it to be merged in the ACL component directly ?

Thanks

**Comment by lisachenko** [comment]
No, bundle is not compatible with sf3 yet.

**Comment by fduch** [comment]
Hi @magnetik.

First of all, this is not a bundle, it's a library.
Since i've tested it with 3.x versions of symfony/security-acl it should work fine with symfony 3.0 (i've also updated deps in composer.json recently: https://github.com/GlobalTradingTechnologies/reverse-search-acl/commit/58c8da19a2c4374ea342e0d00dda8ae4b4040707)

As for you second question.
I'am planning to provide some enhancements and open an issue to talk with symfony maintainers about integrating it in security-acl component but for not it evolves as separate package.
